# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(543, 417)
        Form.setWindowIcon(QtGui.QIcon("icons/images.png"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(120, 120))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/Depression-e1507565838523.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 75 22pt \"Times New Roman\";\n"
"color:rgb(0, 200, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.counter_label = QtWidgets.QLabel(Form)
        self.counter_label.setText("")
        self.counter_label.setObjectName("counter_label")
        self.horizontalLayout_6.addWidget(self.counter_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.l = QtWidgets.QLabel(Form)
        self.l.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(200, 200, 200);")
        self.l.setScaledContents(False)
        self.l.setWordWrap(True)
        self.l.setObjectName("l")
        self.horizontalLayout.addWidget(self.l)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.face_sad_label = QtWidgets.QLabel(Form)
        self.face_sad_label.setMaximumSize(QtCore.QSize(80, 80))
        self.face_sad_label.setText("")
        self.face_sad_label.setPixmap(QtGui.QPixmap("icons/if_face-sad_118878.png"))
        self.face_sad_label.setScaledContents(True)
        self.face_sad_label.setObjectName("face_sad_label")
        self.horizontalLayout_5.addWidget(self.face_sad_label)
        self.face_smile_label = QtWidgets.QLabel(Form)
        self.face_smile_label.setMaximumSize(QtCore.QSize(80, 80))
        self.face_smile_label.setText("")
        self.face_smile_label.setPixmap(QtGui.QPixmap("icons/if_face-smile_118880.png"))
        self.face_smile_label.setScaledContents(True)
        self.face_smile_label.setObjectName("face_smile_label")
        self.horizontalLayout_5.addWidget(self.face_smile_label)
        self.predict_label = QtWidgets.QLabel(Form)
        self.predict_label.setStyleSheet("font: 75 17pt \"Times New Roman\";")
        self.predict_label.setObjectName("predict_label")
        self.horizontalLayout_5.addWidget(self.predict_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(14, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Backbtn = QtWidgets.QPushButton(Form)
        self.Backbtn.setMinimumSize(QtCore.QSize(0, 30))
        self.Backbtn.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/if_arrow-back-outline_216436.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Backbtn.setIcon(icon)
        self.Backbtn.setIconSize(QtCore.QSize(30, 30))
        self.Backbtn.setObjectName("Backbtn")
        self.horizontalLayout_3.addWidget(self.Backbtn)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setMinimumSize(QtCore.QSize(0, 30))
        self.btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn.setFont(font)
        self.btn.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/if_Arrow_Right_1063918.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn.setIcon(icon1)
        self.btn.setIconSize(QtCore.QSize(30, 30))
        self.btn.setObjectName("btn")
        self.horizontalLayout_3.addWidget(self.btn)
        self.horizontalLayout_3.setStretch(1, 9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Depression survey"))
        self.l.setText(_translate("Form", "What is your usual mood ?"))
        self.predict_label.setText(_translate("Form", "TextLabel"))
        self.Backbtn.setText(_translate("Form", "Back"))
        self.btn.setText(_translate("Form", "next"))

# import project_resources_rc
